module.exports = {
  AUTH_FAILED: { status: 401, message: 'AUTH_FAILED' },

  NEW_IAM_ROLE_FAIULRED_WANTED_PARAMETER_LOSTED: { status: 400, message: 'NEW_IAM_ROLE_FAIULRED_WANTED_PARAMETER_LOSTED' },
  NEW_IAM_ROLE_FAIULRED_ROLE_EXISTS: { status: 400, message: 'NEW_IAM_ROLE_FAIULRED_ROLE_EXISTS' },

  NEW_IAM_GROUP_FAIULRED_WANTED_PARAMETER_LOSTED: { status: 400, message: 'NEW_IAM_GROUP_FAIULRED_WANTED_PARAMETER_LOSTED' },
  NEW_IAM_GROUP_FAIULRED_ON_SAVING: { status: 400, message: 'NEW_IAM_GROUP_FAIULRED_ON_SAVING' },

  FETCH_IAM_GROUP_ROLES_FAIULRED: { status: 400, message: 'FETCH_IAM_GROUP_ROLES_FAIULRED' },
  FETCH_IAM_GROUP_ROLES_NO_CONTAIN_ROLE: { status: 204, message: 'FETCH_IAM_GROUP_ROLES_NO_CONTAIN_ROLE' },

  BAD_REQUEST: { status: 400, message: 'BAD_REQUEST' }
}
